### PR TITLE
Fix mbed-tool support

### LINKED ISSUE #6: License & contributions additions
Please look at https://github.com/ARMmbed/mbed-os-example-blinky, and follow:

- adding license headers to files
- adding section to readme about "license and contributions"
- adding contributions md file

### PR DESCRIPTION
**Pull request by harmut01**
## Summary of Changes 

Fixes #6, https://github.com/ARMmbed/mbed-os-example-sd-driver/issues/57

Add license header and clean up code comments.

`.travis.yml`:
  * Update mbed-tools commands

`CMakeLists.txt`:
  * Update the configuration path generated by mbed-tools
  * Remove mbed_set_mbed_target_linker_script() call which is no longer present in Mbed OS.
  * Remove call to mbed_configure_app_target.

### CODE REVIEW

File: main.cpp [hunk 1]
```diff
@@ -1,13 +1,14 @@
+/* mbed Microcontroller Library
+ * Copyright (c) 2019 ARM Limited
+ * SPDX-License-Identifier: Apache-2.0
+ */
 #include "mbed.h"
 #include "LittleFileSystem.h"
 #include "SDBlockDevice.h"
 #include <stdio.h>
 #include <errno.h>
-/* mbed_retarget.h is included after errno.h so symbols are mapped to
```
Comment (0xc0170) [inline main.cpp:6]: this is in the commit for license addition, how is it related? why it was removed?

Comment (harmut01) [reply main.cpp:6]: @0xc0170 i wasn't sure if the commit was relevant seeing as it was added some years ago. Thought it was trivial to clean it up here. Would you recommend I revert the change or move it into another commit?

Comment (0xc0170) [reply main.cpp:6]: own commit +1

**Review by evedon — APPROVED** [review]

**Comment by evedon** [comment]
@harmut01 The PR should be made against the devleopment branch, not master.

**Review by 0xc0170 — APPROVED** [review]

**Comment by 0xc0170** [comment]
Shall we merge this one?

**Review by LDong-Arm — CHANGES_REQUESTED** [review]
It's also worth adding Mbed CLI 2 usage to README.md

File: README.md [hunk 2]
```diff
@@ -148,125 +113,126 @@ the `mbed_app.json` file.
...
+          },
+          "RZ_A1H": {
+               "SPI_MOSI": "P8_5",
+               "SPI_MISO": "P8_6",
+               "SPI_CLK":  "P8_3",
+               "SPI_CS":   "P8_4"
+          }
+     }
+}
+```
```
Comment (LDong-Arm) [inline README.md:235]: IMO there's no need to duplicate the file, as we would have to update both README and the actual file.
Could replace the first mention of `mbed_app.json` above with a link, i.e. in markdown
```markdown
[`mbed_app.json`](./mbed_app.json)
```

File: README.md [hunk 3]
```diff
@@ -330,13 +296,13 @@ The above figure shows the K64F with the v1.0.0 CI test shield fitted. Note:
...
+ ```sh
  mbed --version
  ```
 
  If not, update it:
 
- ```
+ ```sh
  pip install mbed-cli --upgrade
  ```
```
Comment (LDong-Arm) [inline README.md:308]: This is still Mbed CLI 1, even though we added instructions for both 1 and 2. I'm not sure we need this troubleshooting, because the "Mbed OS build tools" section near the top seems enough.

**Review by LDong-Arm — COMMENTED** [review]
A couple of remarks on README.md since this PR updates that.

**Comment by harmut01** [comment]
Cheers @LDong-Arm - do you have any thoughts on [this](https://github.com/ARMmbed/mbed-os-example-sd-driver/blob/10b845527278b9dd84ee2dc85d66d9e8df65bdbd/README.md#target-k64f-with-ci-test-shield-fitted) section? The image the section refers to doesn't exist in the repo anymore, I'm not sure if its worth keeping it in its current state.

**Comment by LDong-Arm** [comment]
@harmut01 From the git history, the image seems missing ever since the link was created.
@ARMmbed/mbed-os-test Is it worth keeping the mentioning of the CI test shield in this example? Or, if we want to fix the image, where can we find one?

**Review by LDong-Arm — APPROVED** [review]

**Review by 0xc0170 — APPROVED** [review]

**Comment by 0xc0170** [comment]
> @ARMmbed/mbed-os-test Is it worth keeping the mentioning of the CI test shield in this example? Or, if we want to fix the image, where can we find one?

Lets get this sorted via a new issue.
